import {mkdir,writeFile,rm,cp} from 'node:fs/promises';
import path from 'node:path';

const root=process.cwd(), out=path.join(root,'site');
await rm(out,{recursive:true,force:true});
for(const d of ['assets','tools','guides','reference','categories']) await mkdir(path.join(out,d),{recursive:true});
for(const f of ['style.css','narrow.css','app.js']) await writeFile(path.join(out,'assets',f),await (await import('node:fs/promises')).readFile(path.join(root,'scripts','assets',f),'utf8'));

const GA=`<!-- Google tag (gtag.js) --><script async src="https://www.googletagmanager.com/gtag/js?id=G-TGT88WMVDG"></script><script>window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments)}gtag('js',new Date());gtag('config','G-TGT88WMVDG');</script>`;
const categories={diagnostics:'Diagnostics & setup',measurement:'Measurement & adjustment',documents:'Shop documents',inspection:'Inspection'};
const tools=[
 ['guitar-setup-wizard','Guitar Setup Wizard','diagnostics','Turn symptoms and measurements into a safe setup order.',['instrument','issue','relief','action','recentChange']],
 ['fret-buzz-diagnostic','Fret Buzz Diagnostic Tool','diagnostics','Prioritize likely buzz causes by location, playing context, and measurements.',['instrument','construction','buzzWhere','stringArea','amplified','relief','action','recentChange','fretCondition','climate']],
 ['high-action-diagnostic','High Action Diagnostic Tool','diagnostics','Separate relief, bridge, nut, and neck-angle clues before adjustment.',['instrument','action','relief','bridgeRoom','firstFret','climate']],
 ['tuning-stability-troubleshooter','Tuning Stability Troubleshooter','diagnostics','Trace tuning drift through strings, nut, hardware, tremolo, and environment.',['instrument','drift','stringsAge','tremolo','binding','hardware','climate']],
 ['intonation-problem-diagnostic','Intonation Problem Diagnostic','diagnostics','Interpret 12th-fret tuner error only after tuning, relief, and action checks.',['instrument','intonation','stringsAge','action','relief','allStrings']],
 ['string-gauge-change-planner','String Gauge Change Planner','measurement','Compare old and new gauges, scale, and tuning before a setup change.',['scale','oldGauge','newGauge','oldTuning','newTuning','tremolo']],
 ['alternate-tuning-string-selector','Alternate Tuning String Selector','measurement','Estimate a practical gauge direction for a tuning change without inventing brand tension data.',['scale','currentGauge','semitones','feel']],
 ['electric-guitar-setup-checklist','Electric Guitar Setup Checklist','diagnostics','Build an ordered, printable electric-guitar setup inspection.',['bridgeType','recentChange','symptoms','measurements']],
 ['acoustic-guitar-setup-checklist','Acoustic Guitar Setup Checklist','diagnostics','Build a non-destructive acoustic setup and humidity inspection.',['symptoms','humidity','neckJoint','measurements']],
 ['bass-setup-checklist','Bass Setup Checklist','diagnostics','Build a bass-specific setup sequence around scale, relief, action, and pickup clearance.',['strings','scale','symptoms','measurements']],
 ['used-guitar-inspection','Used Guitar Inspection Generator','inspection','Generate a repeatable pre-purchase condition inspection.',['instrument','price','neck','frets','electronics','structure','notes']],
 ['neck-relief-measurement','Neck Relief Measurement Helper','measurement','Convert and interpret a measured relief gap as a comparison—not a repair verdict.',['relief','unit','instrument','buzzWhere']],
 ['string-action-converter','String Action Converter','measurement','Convert string height between millimetres and common inch fractions.',['action','unit']],
 ['scale-length-identifier','Scale Length Identifier','measurement','Estimate scale length from nut-to-12th-fret or nut-to-bridge measurements.',['measure','measureType','unit']],
 ['pickup-height-planner','Pickup Height Setup Planner','measurement','Record bass/treble pickup clearance and plan balanced listening tests.',['pickupType','bassGap','trebleGap','unit','symptom']],
 ['setup-measurement-sheet','Setup Measurement Sheet','documents','Create a printable baseline measurement record.',['customer','instrumentName','date','relief','bassAction','trebleAction','pickupBass','pickupTreble','notes']],
 ['before-after-setup-card','Before-and-After Setup Card','documents','Document setup changes without claiming guaranteed outcomes.',['customer','instrumentName','date','before','after','work','notes']],
 ['guitar-condition-report','Guitar Condition Report','documents','Create a practical, printable condition report from observed facts.',['customer','instrumentName','date','condition','structure','playability','electronics','notes']]
].map(([slug,title,category,description,fields])=>({slug,title,category,description,fields}));

const defs={
 instrument:['Instrument','select',['Electric guitar','Acoustic guitar','Bass']], construction:['Construction','select',['Solid-body','Semi-hollow','Acoustic']],
 issue:['Main symptom','select',['Fret buzz','High action','Tuning drift','Intonation','General check']], buzzWhere:['Buzz location','select',['Open string','Frets 1–4','Frets 5–12','Above fret 12','Across neck']], stringArea:['Affected strings','select',['One string','Bass side','Treble side','Most strings']], amplified:['Audible through amplifier?','select',['No','Yes','Not applicable']],
 relief:['Neck relief','number','0.20','0.01'], action:['String action','number','1.75','0.01'], recentChange:['Recent change','select',['None','String gauge','Tuning','Temperature or humidity','Hardware work']], fretCondition:['Fret clues','select',['No visible issue','One raised or worn area','Loose or moving fret','Unknown']], climate:['Climate change','select',['Stable','Recent dry conditions','Recent humid conditions','Large change']],
 bridgeRoom:['Bridge adjustment room','select',['Available','Near limit','Unknown']], firstFret:['First-fret clearance','select',['Comfortable','Feels high','Buzzes open','Not measured']], drift:['When tuning moves','select',['After bends','After tremolo use','During all playing','After storage']], stringsAge:['String condition','select',['Fresh and stretched','Fresh not stretched','Old or corroded','Unknown']], tremolo:['Bridge system','select',['Fixed','Tremolo','Floating tremolo']], binding:['Nut clue','select',['No ping or jump','Pings or jumps while tuning','Unknown']], hardware:['Hardware','select',['Secure','Loose tuner or bridge part','Unknown']],
 intonation:['12th-fret reading','select',['Sharp','Flat','Mixed by string','Not measured']], allStrings:['Pattern','select',['One string','Most strings','All strings similar']],
 scale:['Scale length (inches)','number','25.5','0.01'], oldGauge:['Current high-E gauge','number','9','1'], newGauge:['New high-E gauge','number','10','1'], oldTuning:['Current tuning','select',['E standard','Eb standard','D standard','Drop D']], newTuning:['New tuning','select',['E standard','Eb standard','D standard','Drop D']], currentGauge:['Current high-E gauge','number','10','1'], semitones:['Pitch change (semitones)','number','-2','1'], feel:['Target feel','select',['Similar','Softer','Firmer']],
 bridgeType:['Bridge type','select',['Fixed','Two-point tremolo','Vintage tremolo','Locking tremolo']], symptoms:['Symptoms','text','Describe what you hear or feel'], measurements:['Measurements available','select',['Ruler and feeler gauges','Ruler only','None']], humidity:['Relative humidity (%)','number','45','1'], neckJoint:['Neck/body clue','select',['No visible concern','Action high with low saddle','Gap, movement, or crack','Unknown']], strings:['Number of strings','number','4','1'],
 price:['Asking price','number','500','1'], neck:['Neck condition','select',['Straight/adjustable by observation','Concern or unknown']], frets:['Fret condition','select',['Even wear','Heavy wear or high spots','Unknown']], electronics:['Electronics','select',['All functions pass','Noise/intermittent','Not tested']], structure:['Structure','select',['No visible damage','Crack/movement/repair','Unknown']], notes:['Notes','textarea','Observations, limits, and follow-up'],
 unit:['Input unit','select',['mm','in']], measure:['Measured distance','number','12.75','0.001'], measureType:['Measurement method','select',['Nut to 12th fret','Nut to bridge saddle']], pickupType:['Pickup type','select',['Single-coil','Humbucker','Bass pickup','Other']], bassGap:['Bass-side gap','number','2.5','0.01'], trebleGap:['Treble-side gap','number','2.0','0.01'], symptom:['Balance concern','select',['Balanced','Bass side too loud','Treble side too loud','Stratitis/warble','Unknown']],
 customer:['Customer / owner','text','Optional'], instrumentName:['Instrument','text','Make, model, serial'], date:['Date','date',''], bassAction:['Bass-side action (mm)','number','2.0','0.01'], trebleAction:['Treble-side action (mm)','number','1.6','0.01'], pickupBass:['Pickup bass gap (mm)','number','2.5','0.01'], pickupTreble:['Pickup treble gap (mm)','number','2.0','0.01'], before:['Before measurements','textarea','Relief, action, tuning, symptoms'], after:['After measurements','textarea','Relief, action, tuning, observations'], work:['Work performed','textarea','Reversible adjustments and parts'], condition:['Overall observed condition','select',['Excellent','Good','Fair','Needs attention']], playability:['Playability observations','textarea','Action, relief, fret response']
};

const nav=`<a class="brand" href="/">Guitar Setup <b>Lab</b></a><button class="nav-toggle" aria-expanded="false" aria-label="Toggle menu">Menu</button><nav><a href="/categories/diagnostics.html">Diagnose</a><a href="/categories/measurement.html">Measure</a><a href="/categories/documents.html">Record</a><a href="/guides/setup-order.html">Guides</a></nav>`;
const footer=`<footer><div><strong>Guitar Setup Lab</strong><p>Measure first. Change one variable. Record the result.</p></div><div><a href="/about.html">About</a> · <a href="/contact.html">Contact</a> · <a href="/privacy.html">Privacy</a><p>© 2026 · canghun13@naver.com</p></div></footer>`;
function page({title,description,body,slug='',type='WebPage'}){const url=`https://guitarsetuplab.com/${slug}`;return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title} | Guitar Setup Lab</title><meta name="description" content="${description}"><link rel="canonical" href="${url}"><meta property="og:title" content="${title} | Guitar Setup Lab"><meta property="og:description" content="${description}"><meta property="og:url" content="${url}"><meta property="og:type" content="website"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/assets/style.css"><link rel="stylesheet" href="/assets/narrow.css">${GA}<script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org','@type':type,name:title,description,url,provider:{'@type':'Organization',name:'Guitar Setup Lab',email:'canghun13@naver.com'}})}</script><script src="/assets/app.js" defer></script></head><body><header>${nav}</header><main>${body}</main>${footer}</body></html>`}
function field(k){const [label,type,third,step]=defs[k]; if(type==='select') return `<label>${label}<select name="${k}">${third.map(x=>`<option>${x}</option>`).join('')}</select></label>`; if(type==='textarea') return `<label>${label}<textarea name="${k}" placeholder="${third}"></textarea></label>`; return `<label>${label}<input name="${k}" type="${type}" ${third?`placeholder="${third}"`:''} ${step?`step="${step}"`:''}></label>`}
function related(t){return tools.filter(x=>x.slug!==t.slug&&(x.category===t.category||['neck-relief-measurement','string-action-converter','before-after-setup-card'].includes(x.slug))).slice(0,3)}
for(const t of tools){const body=`<section class="tool-hero"><p class="eyebrow">${categories[t.category]} / field tool</p><h1>${t.title}</h1><p class="lede">${t.description}</p><div class="meter"><span>Observe</span><span>Measure</span><span>Plan</span><span>Record</span></div></section><section class="workspace" data-tool="${t.slug}"><form class="panel tool-form"><h2>Workbench inputs</h2><p class="hint">Use measured facts where available. Blank or unknown values reduce certainty.</p><div class="fields">${t.fields.map(field).join('')}</div><div class="actions"><button type="submit">Run tool</button><button type="reset" class="secondary">Reset</button></div></form><article class="panel result" aria-live="polite"><p class="eyebrow">Result ticket</p><h2>Ready for measurements</h2><p>Complete the inputs, then run the tool. Results remain on this device and are not uploaded.</p></article></section><section class="explain"><div><h2>How to use this tool</h2><ol><li>Bring the instrument to playing condition and tune it.</li><li>Enter observations without guessing at measurements.</li><li>Follow the low-risk checks in order and record changes.</li></ol></div><div><h2>Method, assumptions & limits</h2><p>This tool organizes setup evidence; it cannot inspect wood, frets, hardware, or electrical safety. Reference values are comparison points, not universal targets. Playing style, instrument design, string choice, and climate matter.</p><div class="warning"><strong>Stop if…</strong> you feel abnormal resistance, hear cracking, see wood movement or structural deformation, find an unknown truss-rod condition, or cannot make the required measurement. Do not remove material until the cause is confirmed.</div></div></section><section><h2>Continue the workflow</h2><div class="card-grid">${related(t).map(r=>`<a class="card" href="/tools/${r.slug}.html"><small>${categories[r.category]}</small><strong>${r.title}</strong><span>${r.description}</span></a>`).join('')}</div></section>`;await writeFile(path.join(out,'tools',`${t.slug}.html`),page({title:t.title,description:t.description,slug:`tools/${t.slug}.html`,body,type:'WebApplication'}));}

for(const [key,label] of Object.entries(categories)){const list=tools.filter(t=>t.category===key);const body=`<section class="page-head"><p class="eyebrow">Category hub</p><h1>${label}</h1><p class="lede">Choose a focused tool, then follow its links from symptom to measurement and record.</p></section><section class="card-grid">${list.map(t=>`<a class="card" href="/tools/${t.slug}.html"><small>Interactive</small><strong>${t.title}</strong><span>${t.description}</span></a>`).join('')}</section>`;await writeFile(path.join(out,'categories',`${key}.html`),page({title:label,description:`Interactive guitar ${label.toLowerCase()} tools with measured, safety-first workflows.`,slug:`categories/${key}.html`,body}));}

const home=`<section class="home-hero"><div><p class="eyebrow">Setup, Repair & Luthier Tools</p><h1>Turn guitar symptoms into a measured work order.</h1><p class="lede">A safety-first bench for diagnosing playability, comparing measurements, planning reversible adjustments, and printing a record of the result.</p><div class="actions"><a class="button" href="/tools/guitar-setup-wizard.html">Start setup triage</a><a class="button secondary" href="/categories/measurement.html">Open measurement tools</a></div></div><aside class="ticket"><b>BENCH SEQUENCE / 01</b><ol><li>Listen & locate</li><li>Measure current state</li><li>Change one variable</li><li>Retune & verify</li><li>Record the result</li></ol></aside></section><section><p class="eyebrow">Three connected benches</p><h2>Do the next useful check—not every adjustment at once.</h2><div class="card-grid"><a class="card featured" href="/categories/diagnostics.html"><small>01 / Diagnose</small><strong>Locate the system</strong><span>Separate string, nut, relief, action, fret, bridge, and climate clues.</span></a><a class="card" href="/categories/measurement.html"><small>02 / Measure</small><strong>Build a baseline</strong><span>Convert and interpret relief, action, scale, gauge, and pickup clearance.</span></a><a class="card" href="/categories/documents.html"><small>03 / Record</small><strong>Print the evidence</strong><span>Create shop-ready measurement, before/after, and condition records.</span></a></div></section><section class="bench"><div><p class="eyebrow">Popular starting points</p><h2>What is the instrument telling you?</h2></div><div class="list">${tools.slice(1,7).map(t=>`<a href="/tools/${t.slug}.html"><span>${t.title}</span><i>Open →</i></a>`).join('')}</div></section>`;
await writeFile(path.join(out,'index.html'),page({title:'Guitar Setup, Repair & Luthier Tools',description:'Interactive guitar setup diagnostics, measurement helpers, checklists, and printable shop records.',body:home}));

const basics={
 'about.html':['About Guitar Setup Lab','Why this site treats setup as a measured workflow.',`<section class="page-head"><p class="eyebrow">About the bench</p><h1>About Guitar Setup Lab</h1><p class="lede">We build independent, browser-based tools for players, repair shops, and instrument makers.</p></section><section class="prose"><h2>Our method</h2><p>Setup is a chain of observations. A symptom leads to a measurement; a measurement supports a reversible plan; the result is checked and recorded. The tools here make that chain visible.</p><h2>Safety boundary</h2><p>No browser tool can inspect an instrument. We avoid guaranteed diagnoses, automatic instructions for irreversible work, high-voltage amplifier repair, and exact truss-rod turns. When evidence conflicts, stop and consult a qualified technician.</p><h2>Editorial approach</h2><p>Reference values are labeled as comparison points. Manufacturer procedures and primary technical sources are preferred. Contact: <a href="mailto:canghun13@naver.com">canghun13@naver.com</a>.</p></section>`],
 'contact.html':['Contact','Contact Guitar Setup Lab about tool corrections or accessibility.',`<section class="page-head"><p class="eyebrow">Bench notes</p><h1>Contact</h1><p class="lede">Found a calculation, wording, or accessibility issue? Send the instrument type, page URL, input values, and observed result.</p></section><section class="prose"><h2>Email</h2><p><a class="button" href="mailto:canghun13@naver.com">canghun13@naver.com</a></p><p>Do not send urgent electrical or structural repair requests. A website cannot inspect an instrument or replace an in-person technician.</p></section>`],
 'privacy.html':['Privacy','Privacy details for Guitar Setup Lab and its browser-based tools.',`<section class="page-head"><p class="eyebrow">Policy</p><h1>Privacy</h1><p class="lede">Tool inputs are processed in your browser and are not submitted to our server.</p></section><section class="prose"><h2>Analytics</h2><p>We use Google Analytics 4 to understand aggregate page use. Google may process device, browser, and interaction data according to its policies. This site does not require an account.</p><h2>Local actions</h2><p>Copy and print actions use your browser. Avoid entering sensitive personal data into shop notes on a shared device.</p><h2>Contact</h2><p>Privacy questions: <a href="mailto:canghun13@naver.com">canghun13@naver.com</a>.</p></section>`],
 '404.html':['Page not found','The requested Guitar Setup Lab page could not be found.',`<section class="page-head"><p class="eyebrow">404 / misplaced bench ticket</p><h1>That page is not on this bench.</h1><p class="lede">The address may have changed. Return to the tool index and start from the symptom or measurement.</p><a class="button" href="/">Return home</a></section>`]
};
for(const [file,[title,description,body]] of Object.entries(basics)) await writeFile(path.join(out,file),page({title,description,slug:file,body}));

const guides=[
 ['setup-order','Safe Guitar Setup Order','Why tuning, relief, action, pickup clearance, and intonation should be checked in sequence.',`<h2>A controlled sequence</h2><ol><li>Install or assess stable strings and tune to the intended pitch.</li><li>Inspect structure, hardware, and climate clues.</li><li>Measure neck relief before judging bridge action.</li><li>Measure action on both sides and test the full fretboard.</li><li>Check pickup clearance while fretting the last fret.</li><li>Set intonation last, with a capable tuner.</li></ol><p>Retune after every change. Change one variable at a time so the outcome remains attributable.</p>`],
 ['measure-neck-relief','How to Measure Neck Relief','A repeatable capo, last-fret, and feeler-gauge method for recording relief.',`<h2>Measurement method</h2><ol><li>Tune the instrument and hold it in playing position.</li><li>Capo the first fret.</li><li>Hold the string at the last fret or neck/body joint.</li><li>Measure the gap near the middle of the span with a feeler gauge.</li></ol><p>Record where you measured and which string you used. A value alone does not prove that the truss rod should be adjusted.</p>`],
 ['used-guitar-inspection','Used Guitar Inspection Guide','Inspect structure, neck, frets, hardware, electronics, and playability before purchase.',`<h2>Bring evidence, not optimism</h2><p>Use a tuner, short cable, clean amplifier, flashlight, straightedge or ruler, and permission before adjusting anything. Verify serial and ownership claims separately.</p><h2>Walk the instrument</h2><p>Start with structure and repairs, then neck and truss-rod access, frets, hardware, electronics, acoustic noise, amplified signal, and setup measurements. Price uncertainty into the decision; do not treat the report as a warranty.</p>`]
];
for(const [slug,title,description,content] of guides) await writeFile(path.join(out,'guides',`${slug}.html`),page({title,description,slug:`guides/${slug}.html`,body:`<section class="page-head"><p class="eyebrow">Field guide</p><h1>${title}</h1><p class="lede">${description}</p></section><article class="prose">${content}<div class="warning"><strong>Safety boundary</strong> Stop for abnormal resistance, cracking sounds, visible movement, electrical hazards, or measurements you cannot reproduce.</div></article>`,type:'Article'}));
const refs=[['unit-conversion','Guitar Setup Unit Conversion Reference','Convert common millimetre and inch measurements used at the bench.',`<table><thead><tr><th>Millimetres</th><th>Decimal inches</th><th>Nearby fraction</th></tr></thead><tbody><tr><td>0.10</td><td>0.0039</td><td>≈ 1/256</td></tr><tr><td>0.20</td><td>0.0079</td><td>≈ 1/128</td></tr><tr><td>1.00</td><td>0.0394</td><td>≈ 5/128</td></tr><tr><td>1.50</td><td>0.0591</td><td>≈ 1/16</td></tr><tr><td>2.00</td><td>0.0787</td><td>≈ 5/64</td></tr></tbody></table><p>Fractions are rounded display aids. Use decimal millimetres or inches for calculations.</p>`],['measurement-points','Guitar Setup Measurement Points','A reference for recording where and how each setup measurement was taken.',`<dl><dt>Relief</dt><dd>Gap near mid-span while the string is held at the first and last fret/body joint.</dd><dt>Action</dt><dd>Gap from fret crown to string underside at a named fret.</dd><dt>Pickup clearance</dt><dd>Gap from pole/top to string underside while fretting the last fret.</dd><dt>Scale</dt><dd>Twice nut-to-12th-fret is the nominal scale; saddle positions include compensation.</dd></dl>`]];
for(const [slug,title,description,content] of refs) await writeFile(path.join(out,'reference',`${slug}.html`),page({title,description,slug:`reference/${slug}.html`,body:`<section class="page-head"><p class="eyebrow">Bench reference</p><h1>${title}</h1><p class="lede">${description}</p></section><article class="prose">${content}</article>`,type:'Article'}));

const publicFiles=['index.html',...Object.keys(basics),...Object.keys(categories).map(x=>`categories/${x}.html`),...tools.map(t=>`tools/${t.slug}.html`),...guides.map(x=>`guides/${x[0]}.html`),...refs.map(x=>`reference/${x[0]}.html`)];
await writeFile(path.join(out,'sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${publicFiles.filter(x=>x!=='404.html').map(x=>`<url><loc>https://guitarsetuplab.com/${x==='index.html'?'':x}</loc></url>`).join('')}</urlset>`);
await writeFile(path.join(out,'robots.txt'),'User-agent: *\nAllow: /\nSitemap: https://guitarsetuplab.com/sitemap.xml\n');
await writeFile(path.join(out,'llms.txt'),'# Guitar Setup Lab\n\nInteractive guitar setup diagnostics, measurement helpers, and printable records.\n\n- Tools use safety-first, measurement-led workflows.\n- No result is a physical inspection or guaranteed repair diagnosis.\n- Contact: canghun13@naver.com\n');
await writeFile(path.join(out,'CNAME'),'guitarsetuplab.com\n');
await writeFile(path.join(out,'.nojekyll'),'');
await writeFile(path.join(out,'favicon.svg'),`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="12" fill="#17201d"/><path d="M13 38h38M16 26h32M22 18v28M42 18v28" stroke="#e1a955" stroke-width="4"/><circle cx="32" cy="32" r="6" fill="#e9eee8"/></svg>`);
// The repository is configured for GitHub Pages branch/root publishing. Mirror the
// reviewed deployment artifact into root so Pages and the local `site/` build agree.
for(const entry of ['assets','tools','guides','reference','categories',...Object.keys(basics),'index.html','sitemap.xml','robots.txt','llms.txt','CNAME','favicon.svg','.nojekyll']) await cp(path.join(out,entry),path.join(root,entry),{recursive:true,force:true});
console.log(`Built ${publicFiles.length} public HTML pages and ${tools.length} tools.`);
