const P=(prepare,method,example,interpret,limits)=>({prepare,method,example,interpret,limits});

export const toolDepth={
  'guitar-setup-wizard':P('Tune to the intended pitch, identify the installed strings, and record relief and action before touching an adjustment. Note whether the symptom began after transport, weather, or a parts change.','The wizard orders evidence by dependency: structural and string condition first, then relief, action, pickup clearance, and intonation. A later measurement is not used to excuse an earlier unresolved fault.','A 25.5-inch electric arrives with fresh 10–46 strings, 0.20 mm relief, 2.4 mm bass action, and buzz above fret 12. The useful result is to inspect upper-fret and bridge geometry before reducing relief; the next action is a mapped fret test.','Treat the ticket as an inspection order. A high-priority branch means verify that cause next, not that the cause has been proven. Recheck tuning after every single-variable change.','Playing attack, fret condition, neck angle, and measurement position can change the same numbers. The wizard cannot assess truss-rod engagement or authorize cutting, leveling, or neck-joint work.'),
  'fret-buzz-diagnostic':P('Use stable strings and normal playing position. Map the first and last buzzing frets on each affected string, then compare unplugged and amplified behavior.','Location patterns are combined with relief, action, construction, recent changes, and fret condition. Open-string, low-position, middle-neck, and upper-neck buzz produce different inspection priorities.','If only the low E buzzes at frets 7–9, relief is 0.10 mm, bass action is 1.5 mm, and the other strings are clear, the result should prioritize local fret or string evidence instead of a global neck adjustment.','A ranked cause is a test queue. Confirm it with a fret rocker, repeated measurement, or controlled action change before altering the instrument. Amplified absence may make benign acoustic rattle acceptable.','Uneven attack, twisted necks, loose hardware, sympathetic vibration, and worn strings can imitate fret buzz. No entered pattern proves that fret leveling or truss-rod adjustment is required.'),
  'high-action-diagnostic':P('Measure relief and 12th-fret action in playing position, check first-fret clearance, and document remaining bridge travel. For acoustics, observe saddle exposure without removing material.','The decision tree separates curvature, nut-end clearance, bridge height, and neck projection because each changes a different region of the string path.','An acoustic with 0.20 mm relief, 3.2 mm bass action, normal first-fret clearance, and very little saddle above the bridge points toward geometry assessment rather than simply lowering the saddle.','Use the result to choose the next measurement: relief when the whole middle span is high, nut clearance when first-position fretting is stiff, or projection when bridge travel is exhausted.','Top movement, neck-joint condition, fret height, playing force, and measurement fret affect interpretation. The tool never calculates a safe amount of saddle removal or neck-joint alteration.'),
  'tuning-stability-troubleshooter':P('Fit and stretch stable strings, tune upward to pitch, and note whether drift follows bends, tremolo use, temperature, or time. Mark tuner-post wraps and inspect hardware visually.','The troubleshooter uses substitution and event timing to separate string settling, nut friction, tuner movement, bridge return, and environmental drift.','If pitch returns sharp after a bend, a ping is heard near the nut, and another set of strings behaves the same, the next check is nut friction and witness-point movement—not random tuner tightening.','Compare direction and trigger. All strings drifting together suggests a system or climate change; one string behaving differently suggests its own path, wrap, saddle, or hardware.','A tuner display cannot locate physical binding. Tremolo knife edges, loose neck joints, damaged tuners, and incorrectly cut slots need direct inspection; lubricant is not a cure for bad geometry.'),
  'intonation-problem-diagnostic':P('Install stable strings, tune accurately, verify relief and action, and compare the fretted 12th note with the open note or 12th-fret harmonic using consistent fretting pressure.','The result interprets error direction only after setup dependencies. A sharp fretted note generally needs a longer speaking length; a flat note generally needs a shorter one, subject to bridge design.','With the open E centered and the fretted 12th reading 7 cents sharp on an otherwise stable string, the controlled next step is a small saddle move away from the nut, retune, and retest.','Look for a repeatable per-string pattern. Similar errors across every string can indicate measurement, tuning, scale, or setup problems rather than six independent saddle faults.','Old strings, excessive fretting force, high nut slots, magnetic pull, compensated systems, and limited saddle travel distort simple direction rules. The tool does not prescribe irreversible bridge relocation.'),
  'string-gauge-change-planner':P('Record the current brand, construction, gauges, scale, and tuning before choosing a candidate. Note floating tremolo position and present setup measurements.','The planner compares diameter and pitch direction as a risk screen. It deliberately avoids exact force claims when published unit weight for the actual string is unavailable.','Changing a 25.5-inch guitar from 9–42 in E standard to 10–46 in E-flat mixes heavier strings with lower pitch. The result should call for stabilization and remeasurement, not assert an exact net tension.','Use the checklist to plan nut movement, relief, tremolo balance, action, and intonation checks. “Likely higher” or “mixed” is a direction, not a force value.','Equal gauge does not guarantee equal unit weight across constructions or brands. Slot fit, core shape, winding, scale, and playing feel require observation; never widen a nut from diameter alone.'),
  'alternate-tuning-string-selector':P('Start from a string set whose feel you know. Enter scale and semitone change for the string being evaluated, then state whether the goal is similar, firmer, or looser feel.','For the same construction and scale, tension follows frequency squared and approximately follows unit weight. The selector uses pitch ratio for direction while avoiding invented product data.','Dropping one whole step is −2 semitones; frequency becomes about 0.891 of the original and same-string tension about 0.794. A slightly heavier candidate may restore feel, but published unit weight is needed for an exact match.','Read the recommendation as a candidate range for comparison. Test tuning stability, nut movement, relief, and intonation after installing the actual product.','Gauge-to-unit-weight relationships are not universal, especially across wound, coated, flatwound, and different core designs. The selector cannot predict tone, stiffness, or safe nut-slot width.'),
  'electric-guitar-setup-checklist':P('Identify bridge type, intended tuning, installed set, and recent work. Capture neck relief, bass/treble action, pickup clearance, and an amplified symptom map. Photograph floating-bridge position and note whether locking hardware is engaged before beginning.','The generated order protects dependencies: strings and structure, tuning, relief, bridge action, pickup clearance, intonation, then full-neck and control tests.','For a floating bridge that rose after moving from 9–42 to 10–46, record the present bridge angle and tune repeatedly before judging action. The checklist then routes to tension and spring-balance checks.','A checked item means it was observed under named conditions, not that it met a universal specification. Record unchanged items and failed tests as carefully as adjustments.','Bridge designs, manufacturer procedures, active electronics, locking systems, and fret condition require model-specific knowledge. Do not force truss rods, posts, or seized hardware.'),
  'acoustic-guitar-setup-checklist':P('Stabilize the instrument in a measured humidity range, inspect the top and bridge, tune to the intended pitch, and record relief, action, first-fret clearance, and saddle exposure.','The sequence puts humidity and structure ahead of setup because top movement and neck-joint geometry can dominate action on an acoustic instrument.','An acoustic at 28% relative humidity with sharp fret ends and a visibly sunken top should be stabilized and inspected before a low saddle or relief number is treated as a normal setup problem.','Use the result to distinguish a condition-monitoring task from an adjustment task. Re-measure after acclimation using the same ruler, position, and fret.','Humidity readings vary by sensor and location. Bracing, bridge adhesion, neck reset need, and saddle break angle cannot be established from form entries; removal of saddle or bridge material is outside scope.'),
  'bass-setup-checklist':P('Record scale, string count, tuning, construction, and installed gauges. Measure relief and action on both outer strings and test every fret with normal right-hand attack.','Bass setup uses the same dependency chain as guitar but retains bass-specific scale, string mass, pickup pull, and playing-force observations.','A 34-inch four-string with 45–100 strings, 0.30 mm relief, and clean notes except above fret 15 should receive an upper-register fret and bridge check before global relief is increased.','Compare results across strings and registers. A locally high action value, a global value, and a pickup-related warble lead to different next tests.','Multi-scale basses, unusual bridge geometry, heavy attack, tapered strings, and manufacturer pickup limits need direct specifications. The checklist does not define one correct action or relief.'),
  'used-guitar-inspection':P('Bring a tuner, flashlight, short known-good cable, clean amplifier or interface, and measuring rule. Ask permission before removing covers or adjusting anything.','The report separates identity, visible structure, neck and frets, hardware, electronics, acoustic noises, amplified behavior, and measured setup. Observations remain distinct from inferred repair cost.','A used electric priced at $700 shows fret wear under strings 1–3, intermittent output when the jack moves, and no visible neck crack. Record each fact and price a professional assessment instead of labeling the guitar “good” or “bad.”','Use “not tested” whenever access or conditions are missing. A failed item identifies uncertainty for negotiation or inspection; it is not a remote diagnosis.','Serial numbers do not prove ownership or authenticity. Hidden repairs, truss-rod range, internal moisture damage, and intermittent faults may escape a short inspection. The generator is not a warranty.'),
  'neck-relief-measurement':P('Tune the instrument, hold it in playing position, capo fret 1, fret the same string at the last fret or neck joint, and measure the middle-span gap with a feeler gauge.','The helper converts the entered gap and places it in context with instrument type and buzz location. It preserves the raw measurement rather than calculating a truss-rod turn.','A recorded 0.20 mm gap converts to about 0.0079 inch. If buzz remains only above fret 15, that number does not justify adding relief; inspect the upper fret and action pattern next.','Repeat the same datum three times. Use change over time and symptom correlation rather than a single generic target. Record the fret where the gap was taken.','Capo pressure, string choice, measurement span, neck profile, temperature, and playing force affect the reading. Relief alone cannot reveal a twist, loose fret, or safe adjustment direction.'),
  'string-action-converter':P('Measure from the top of a named fret to the underside of the string with the instrument tuned and in a repeatable position. State the unit and fret.','The converter applies exact inch–millimetre conversion, with one inch equal to 25.4 mm, then reports nearby common fractions for communication.','An action of 1.6 mm equals about 0.0630 inch, close to 4/64 inch. Record 1.6 mm as the measured value; the nearby fraction is a readable comparison, not extra precision.','Use the converted value to compare records that share the same fret and method. Differences smaller than the ruler resolution should not be treated as real changes.','Conversion does not correct parallax, string deflection, fret wear, or differing measurement locations. It also does not determine whether an action value is appropriate for a player.'),
  'scale-length-identifier':P('Locate the nut witness point, measure to the center of fret 12 or to the actual bridge witness point, and keep the ruler aligned with the string path.','A nut-to-12th measurement is doubled to estimate nominal scale. Nut-to-bridge measurements are compared with common families but can include saddle compensation.','A nut-to-12th distance of 323.85 mm doubles to 647.70 mm, essentially 25.5 inches. A bridge measurement a few millimetres longer may simply include normal compensation.','Prefer the doubled 12th-fret result when the fret is accessible. Use the bridge result as a cross-check and report measurement uncertainty rather than forcing a catalog label.','Compensated nuts, individual saddles, fan frets, inaccurate witness-point selection, and damaged frets can shift readings. The identifier cannot authenticate a model.'),
  'pickup-height-planner':P('Tune normally, fret the last fret, and measure from each pole or cover to the underside of its string on bass and treble sides. Record pickup type and the audible symptom.','The planner treats clearance as a repeatable baseline and recommends listening comparisons. It does not embed a universal height because magnetic design and manufacturer guidance differ.','If a neck pickup measures 1.5 mm on the bass side and low notes warble, lower that side by a small reversible amount, retune, and compare a recorded phrase at matched volume.','Balance level, clarity, sustain, and pitch stability across pickup positions. Preserve the starting measurements so a listening test can be reversed.','Pole stagger, rail designs, active pickups, string magnetism, pickup angle, and mounting travel change the result. Contact, stripped screws, or abnormal resistance require stopping.'),
  'setup-measurement-sheet':P('Use one instrument, tuning, string set, playing position, date, and measurement method. Capture raw values before any adjustment.','The sheet groups identity, environment, relief, action, pickup clearance, and notes so later before/after comparisons use the same datums.','Record “relief 0.18 mm, capo 1/held 17/measured 8” and “action bass 2.0 mm at fret 12,” not just “neck good.” After work, repeat those exact methods.','Blank fields signal missing evidence; they are preferable to guessed numbers. Print or save the completed ticket with the job record.','The sheet does not validate whether a value is suitable, and browser storage is not a shop backup. Avoid sensitive customer data on shared devices.'),
  'before-after-setup-card':P('Define the complaint, test conditions, and measurement points before work. Keep “before,” work performed, and “after” in separate fields.','The card creates an attributable change record. It emphasizes one-variable changes and repeat tests instead of outcome promises.','Before: bass action 2.6 mm at fret 12 and relief 0.35 mm. Work: stabilized tuning and adjusted relief within service procedure. After: 2.3 mm and 0.22 mm, with remaining fret-15 rattle noted.','A useful card shows both improvement and unresolved behavior. Include the final tuning, string set, and player test rather than writing only “setup complete.”','Different strings, humidity, posture, or tools can invalidate comparison. The document is a service record, not proof that future climate or wear will preserve the result.'),
  'guitar-condition-report':P('Inspect in good light and test each available system without disassembly beyond permission. Describe visible facts, playability, electronics, structure, and items not tested.','The report separates observation from diagnosis and uses consistent condition categories. Notes carry the evidence behind any summary rating.','Write “output cuts when plug moves laterally; second cable behaves the same,” not “needs new jack.” The next action is authorized internal inspection and continuity testing.','Readers should be able to reproduce the test and understand uncertainty. Photographs or job references can be named in notes, but unavailable tests remain explicit.','A surface inspection cannot expose hidden cracks, previous routing, truss-rod range, or intermittent failures. This report is not an appraisal, authenticity certificate, or warranty.'),
  'guitar-repair-intake':P('Record customer language verbatim, instrument identity, included accessories, visible arrival condition, requested priority, budget preference, and permissions.','The form prevents intake observations from becoming a premature diagnosis. It connects reported symptoms to later quote and job records with dates and identifiers.','Customer says “cuts out after ten minutes”; intake observes a loose jack nut but does not open the guitar. Record the case and strap as included, authorize diagnosis, and contact before extra work.','Review the printed ticket with the customer. “Permission to diagnose” does not imply approval for parts, destructive work, or an unlimited bill.','This practical record is not legal advice or a liability waiver. Local consumer rules and shop policies may require additional terms, signatures, privacy handling, or retention controls.'),
  'repair-quote-generator':P('Enter each labor and parts row with description, quantity, and unit amount. Select currency, tax basis, discount, deposit, validity, and assumptions before calculating.','Line amounts are converted to integer cents, then labor and parts subtotals, discount, tax, total, deposit, and balance are calculated in a fixed order to avoid binary rounding drift.','Labor “setup | 2.5 | 60” is $150; parts “strings | 2 | 12.50” is $25. With $5 discount, 10% tax, and $50 deposit, total is $187 and balance $137.','Check every subtotal against shop policy, especially whether tax follows discount and which lines are taxable. The printed quote should name excluded work and an approval path.','Tax, currency, deposit, and quote-enforcement rules vary by jurisdiction. The tool does not process payment, lock prices, manage inventory, or create a legal contract.'),
  'parts-labor-job-sheet':P('Start from the approved job number and quote. Keep diagnosis, authorized work, actual labor, installed parts, before/after measurements, and final test distinct.','The sheet forms a technician timeline: intake evidence, diagnosis, work performed, consumed resources, verification, extra issues, and pickup state.','Job 1042 records 1.5 labor hours, one 10–46 set, relief from 0.30 to 0.20 mm, and a passed control/fretboard test. An unapproved worn nut is listed under additional issues, not completed work.','The final test should name tuning, pickup positions, controls, and remaining limitations. Reconcile quantities and time with the quote before customer pickup.','A generated sheet is not inventory, accounting, or authorization software. Shops need their own retention, privacy, warranty, and change-approval procedures.'),
  'customer-approval-checklist':P('Review diagnosis, estimated cost, contact threshold, replacement preferences, old-parts return, cosmetic risk, custom settings, and notification method with the customer.','The checklist captures a conversation and routes exceptions back to the quote. It deliberately avoids pretending that a browser checkbox is a legally sufficient signature.','A customer approves a $180 setup and fret assessment but requests contact before any work exceeding $220 and wants replaced parts returned. Those limits belong on both approval and job sheet.','Use unresolved or declined items to constrain the work order. Confirm dates and instrument identity before printing, then retain according to shop policy.','Consent and electronic-signature requirements vary. This page provides operational prompts only; it does not verify identity, store an audit trail, or replace jurisdiction-specific terms.'),
  'maintenance-schedule':P('Record actual use, transport, humidity exposure, string type, bridge, electronics, storage, last service, and cleaning habit.','The schedule increases inspection frequency with exposure and usage while keeping condition-triggered checks separate from calendar reminders.','A weekly-gigged electric with a floating tremolo and active electronics receives frequent string, fastener, battery, and bridge-position checks; a cased occasional instrument receives a lighter routine.','Treat dates as prompts to inspect, not automatic instructions to replace or adjust. Record the condition found so later intervals can be refined.','Corrosion, sweat chemistry, climate, hardware design, and manufacturer service intervals vary. Battery leakage, structural movement, or electrical heat overrides the schedule and requires immediate attention.'),
  'ground-hum-diagnostic':P('Turn monitoring level down before reconnecting. Test a direct path with one known-good cable, then compare another instrument, room or circuit, and safe amplifier/interface.','Substitution results isolate source domains. Volume-zero, touch, pickup-position, gain, cable, room, pedalboard, jack, and control behavior are combined without directing mains-equipment repair.','If hum remains with guitar volume at zero but disappears with another cable, cable replacement outranks shielding work. If another guitar hums in the same room, investigate environment before opening either instrument.','A result names the next safe isolation test. Touch behavior is evidence about the signal and environment, not permission to modify protective earth.','Single-coil hum can be normal. Never open amplifiers, power supplies, or mains devices; stop for shocks, heat, odor, damaged power leads, or unclear grounding.'),
  'pickup-phase-troubleshooter':P('Compare each pickup alone and together at matched settings. Record pickup heights, recent replacements, maker, conductor access, split state, and whether thinness and volume loss occur only in combination.','The logic distinguishes polarity/phase interaction from a weak pickup, height imbalance, series/parallel selection, or split-coil state.','Both pickups sound full alone, but together the sound becomes thin and drops sharply after a replacement from another maker. The next action is to verify documented lead functions and magnetic/electrical phase.','Combination-only cancellation is stronger phase evidence than “one pickup sounds quiet.” Measure DC continuity only on an isolated, unpowered circuit and preserve the original wiring map.','Manufacturer color codes are not universal, and magnetic polarity differs from electrical phase. Active systems and proprietary switching require their own documentation.'),
  'pickup-wiring-selector':P('Identify pickup family and exact conductor functions from manufacturer documentation. Count pots, switch poles/throws, cavities, and desired combinations before buying hardware.','The selector compares requested functions with accessible coil junctions and available switch contacts. It flags mutually competing connections rather than inventing a color-code diagram.','Two four-conductor humbuckers, two push-pull DPDT pots, and a three-way toggle can support selected coil-split or series/parallel functions, but exact simultaneous options depend on contact allocation.','Use the result as a requirements list for a verified schematic. Label every lead and photograph stock wiring before desoldering.','Cavity depth, grounding scheme, active preamps, superswitch layouts, and maker-specific wire colors are outside generic selection. Disconnect from amplifiers and power before continuity work.'),
  'potentiometer-value-selector':P('Identify passive or active electronics, pickup family, current measured or marked pot value, control layout, cable load, and the specific brightness problem.','For passive pickups, resistance is treated as part of the pickup load: higher values generally load less and preserve more high-frequency response. The result remains comparative.','Moving a passive humbucker circuit from 250 kΩ toward 500 kΩ may preserve more top end, but a long high-capacitance cable can still dominate. Measure actual pot tolerance before attributing the change.','Compare a reversible test or manufacturer scheme before purchase. “Brighter” is a system tendency, not an exact frequency response or quality rating.','Active systems commonly require maker-specified values. Pickup inductance, tone network, taper, tolerance, wiring, cable, and amplifier input prevent a pot value from predicting exact sound.'),
  'tone-capacitor-comparison':P('Record capacitor values in nanofarads, pot value, pickup family, desired roll-off, and whether the task is a relative comparison or simple RC reference.','The tool can calculate f=1/(2πRC) as a reference and compare value ratios. It explicitly does not model the pickup as an ideal source.','With 500 kΩ and 22 nF, the simple RC reference is about 14.47 Hz; 47 nF yields about 6.77 Hz. Those numbers do not equal the guitar’s audible resonance cutoff.','Use the ratios to understand why a larger capacitor tends toward a darker fully rolled-off range, then audition values in the actual circuit.','Pickup inductance and resistance, pot position, amplifier input, cable capacitance, capacitor tolerance, and wiring topology dominate the real response. Discharge and isolate powered circuits.'),
  'series-parallel-coil-split-selector':P('Verify a humbucker has independently accessible coil leads, identify the series link from maker documentation, and inventory switch contacts and desired noise behavior.','The selector compares series, parallel, and split availability. It reports relative output, clarity, and hum-canceling tendencies without assuming universal colors or coil orientation.','A four-conductor humbucker on a DPDT push-pull can often select series/parallel or a split function. Series is generally fuller; parallel is generally clearer while potentially retaining hum cancellation.','Choose the mode whose tradeoff fits the requirement, then use a pickup-specific schematic. Expect a level change and test every switch state before closing the cavity.','Stacked, rail, active, and proprietary pickups may not follow standard assumptions. Coil split usually loses hum cancellation; exact output and polarity require measurement.'),
  'string-tension-matcher':P('Select supported instrument, scale, tuning, and exact gauge/construction tokens for both sets. Confirm that the installed product matches the published unit-weight table.','Each string uses T=(UW×(2LF)²)/386.4 in pounds, where UW is unit weight, L scale in inches, and F frequency in hertz. Newton display converts pounds after calculation.','For a supported 25.5-inch 10p,13p,17p,26w,36w,46w set in E standard, the fixture totals about 103.6 lb; dropping only the sixth string to D lowers that string’s force.','Compare per-string and total changes, not total alone. A large imbalance on one string can affect feel and tremolo behavior even when totals are close.','Results apply only to the cited D’Addario XL nickel-wound unit weights and supported tokens. Other brands, constructions, corrosion, speaking length, and tuning accuracy can differ.'),
  'fret-position-template':P('Confirm nominal scale between nut and theoretical saddle line, choose one unit, name the nut witness point, and verify the calibration bar before transferring a mark.','Cumulative fret coordinate is d=s−s/2^(n/12). Adjacent spacing is the difference between successive coordinates; internal millimetres retain precision until display.','At 25.5 inches, fret 12 is 12.750 inches from the nut and fret 24 is 19.125 inches. Those invariants make useful checks before relying on the full table.','Compare nut-to-fret cumulative values against an independent rule or CAD fixture. Saddle compensation does not move nominal 12-TET fret slots.','The model does not design temperament offsets, nut compensation, kerf, slot depth, fret crown, or structural margins. A printed scale must pass both calibration bars physically.'),
  'fret-slot-print-template':P('Choose scale, fret count, strip width, paper, orientation, overlap, mark length, and label interval. Measure the 50 mm calibration entry before generating corrected output.','The generator lays 12-TET slot coordinates onto printable tiles with ordered overlap and registration marks. Page geometry is separate from browser and printer scaling.','A 25.5-inch, 24-fret strip on Letter paper may require several ordered tiles. Print at Actual size, measure 50 mm and 2 inches, then align the overlap marks without accumulating edge error.','A correct PDF page box is only the digital stage. Reject the template if either physical bar falls outside tolerance or adjacent-tile marks disagree.','Printer drivers, viewers, humidity, paper stretch, trim, blade kerf, and registration introduce error. Never cut slots from an unverified print or infer slot depth from the lines.'),
  'nut-string-spacing':P('Measure nut width and define whether outside margins reference string edges or centers. Enter installed string diameters in one unit and choose equal-center or equal-gap layout.','Equal-center divides outer-center spread evenly. Equal-gap subtracts string radii and distributes open space so adjacent edge gaps match despite mixed gauges.','For six mixed gauges, equal-center produces identical center intervals but visibly tighter open space beside the heavy strings. Switching to equal-gap changes the center coordinates while preserving chosen outer references.','Compare both tables and verify outer-string clearance over fret bevels on the actual neck. Transfer center marks only after the physical margin definition is confirmed.','No calculator supplies a universal edge margin, ergonomic preference, slot width, or safe cutting depth. Real gauges, fret bevel, player technique, and nut material matter.'),
  'bridge-string-spacing':P('Measure the bridge footprint, desired outer-string center spread, saddle width, real gauges, and bridge type. Identify mechanical saddle limits before selecting a spacing method.','The tool calculates center coordinates and neighboring edge gaps within the entered spread. Equal-gap adjusts center distances for mixed diameters; it does not move hardware beyond its range.','With a 52 mm outer-center spread across six strings, equal-center intervals are 10.4 mm. Mixed gauges make their physical edge gaps unequal; equal-gap redistributes those center intervals.','Check every calculated center against saddle slots, pickup pole coverage, neck taper, and outer-fret clearance. The result is a layout comparison, not a drilling template.','Bridge castings, slotted saddles, string angle, tremolo plates, and manufacturer dimensions constrain placement. Do not drill or file until a full physical mock-up clears all systems.'),
  'fretboard-radius-matcher':P('Use a straight chord of known width and measure perpendicular center sagitta without pressing a flexible surface. Repeat the reading and keep all values in one unit.','For chord c and sagitta h, circular radius R=c²/(8h)+h/2. The tool also perturbs h to show how small depth errors change a large radius estimate.','A 2.000-inch chord with roughly 0.0418-inch sagitta returns close to a 12-inch radius. A small sagitta error noticeably changes the answer, demonstrating measurement sensitivity.','Trust a cluster of repeated readings more than a rounded label. Compare with a known radius gauge and observe whether the board is compound or worn.','The equation assumes a circular arc and an accurate chord. Fret crowns, compound boards, fall-away, tool tilt, string grooves, and surface wear violate that simple model.'),
  'saddle-radius-planner':P('Record fretboard radius model, reference positions, bridge location, string count and spacing, desired per-string action, and real diameters. Use one named vertical datum.','Circular arc offsets are calculated at each string center, then combined with entered action and gauge terms as relative saddle-center targets. Compound radius is interpolated only over the declared reference.','On a six-string 12-inch model, outer string centers sit higher on the arc than the center. Different desired actions further change saddle tops, so copying a bare 12-inch gauge is only a starting comparison.','Read offsets relative to the stated datum and verify with strings tuned. Adjust one saddle reversibly, retune, and check action and radius together.','Bridge mechanics, fret wear, string stiffness, neck relief, compensation, and manufacturer saddle geometry are not solved here. The output is not a machining drawing.'),
  'multiscale-fretboard-planner':P('Enter treble and bass scales, string count, fret count, perpendicular fret, and measured nut/bridge outer-string spreads. Define which side is treble before marking.','Each string receives its own 12-TET distances; nut and bridge endpoints are positioned so the selected fret lies on the chosen perpendicular line, producing 2D fret intersections.','A seven-string plan with 25-inch treble, 27-inch bass, and fret 8 perpendicular should collapse to ordinary straight frets if both scales are changed to the same value—an important fixture.','Inspect coordinate ordering, scale endpoints, and the exact perpendicular fret. Export coordinates into a full drawing that includes neck taper and physical margins.','The planner omits fret-slot kerf, nut compensation, bridge compensation, fretboard edge, binding, overhang, structural layout, and ergonomic validation. Do not cut from coordinates alone.'),
  'neck-angle-planner':P('Establish body plane, scale-direction projection run, bridge string height, fretboard and fret height, desired action, and pocket depth from one coherent side-view datum.','The model subtracts the neck-plane stack from the required bridge string line, then uses atan(rise/run) for a small-angle projection. Values are geometric, not construction tolerances.','If the required rise over a 600 mm run is 10 mm, the geometric angle is about atan(10/600)=0.955 degrees. Recheck every stack component before treating that as a design candidate.','Use the result to compare bridge, pocket, fretboard, and action assumptions. A sign reversal or unexpectedly large angle usually indicates mixed datums.','Top carve, neck flex, bridge adjustment range, compression, fretwork, finish, and joint structure are omitted. The tool never authorizes routing a pocket or altering a set neck.'),
  'headstock-break-angle':P('Measure horizontal run from nut witness point to post or tree and perpendicular height difference from the same string plane. Observe actual string contact and winding direction.','Break angle is atan(height difference/run). Optional tree geometry is calculated independently so the two contact paths are not confused.','A 10 mm drop over an 80 mm run gives about 7.1 degrees. A string tree closer to the nut can create a larger angle from a smaller drop.','Compare strings and look for enough stable witness-point contact without excessive friction. Use tuning behavior and manufacturer geometry alongside the number.','Post diameter, wrap stack, nut slot shape, tree friction, headstock flex, and three-dimensional lateral path are outside the side-view triangle. No universal ideal angle is asserted.'),
  'tremolo-spring-balance':P('Identify bridge design, supported string set and tuning, spring count and arrangement, present and target bridge angle, and remaining claw travel. Photograph the starting state.','The planner combines documented string-tension direction with mechanical observations. It does not convert total string force into screw turns because spring constants and lever arms are unknown.','A supported set change that raises total tension while a floating bridge rises above target indicates rebalancing and repeated tuning. Three springs at a near-limit claw may instead require hardware assessment.','Use the result as a tune–observe–small adjustment–retune loop under the bridge maker’s procedure. Confirm the final angle, action, and intonation.','Spring age, anchor position, bridge lever geometry, friction, and unsupported strings prevent precise turn predictions. Stop at mechanical limits, damaged screws, or unclear knife-edge condition.'),
  'shim-thickness-planner':P('Enter desired angular comparison, actual shim length, full pocket length, and one unit. Confirm which end is thick and whether the proposed shim supports the intended area.','Thickness difference is length×tan(angle). The tool reports both entered-shim and full-pocket taper so a short strip is not mistaken for a full-contact wedge.','A 1-degree change across 60 mm produces about 1.047 mm thickness difference; across a 76.2 mm pocket it is about 1.330 mm. Those are geometric comparisons, not prescriptions.','Check angle sign, thick-end orientation, bridge travel, and neck projection with a reversible mock-up. Re-measure after strings reach pitch.','Material compression, pocket fit, screw load, finish, joint design, and structural contact are not modeled. Avoid improvised point loads or permanent cutting without qualified assessment.')
};

const categoryContext={
 diagnostics:'Diagnostic tools rank observations and controlled checks. They do not identify a defect from one symptom, and their safest output is often the next measurement rather than an adjustment.',
 measurement:'Measurement tools are useful only when the physical datum, unit, fret or position, instrument posture, and instrument state are recorded with the number.',
 documents:'Shop documents preserve who observed what, under which conditions, and with which permission. They are operational records rather than legal, payment, or customer-management systems.',
 inspection:'Inspection tools preserve visible evidence and untested areas. They separate condition notes from diagnosis, valuation, authenticity, and warranty claims.',
 electronics:'Electronics tools begin with safe substitution and documented passive-circuit checks. They exclude amplifiers, power supplies, mains wiring, and energized work.',
 luthier:'Geometry tools apply explicit models to named measurements. A coordinate or angle must still be checked against a physical drawing, real hardware, tolerances, and material behavior.'
};

const fieldRole=(label,type)=>{
  const l=label.toLowerCase();
  if(l.includes('unit')) return 'sets the interpretation and display unit; do not mix units elsewhere in the same run';
  if(l.includes('date')) return 'anchors this record in time so climate, strings, and later work can be compared';
  if(l.includes('tuning')) return 'defines the pitch state that must remain stable while measurements are taken';
  if(l.includes('scale')) return 'defines speaking length or the geometric reference used by the calculation';
  if(l.includes('gauge')||l.includes('diameter')) return 'records the actual string dimensions or supported set rather than a visual estimate';
  if(l.includes('relief')) return 'records neck curvature under the stated capo, fret, position, and tuning method';
  if(l.includes('action')||l.includes('height')||l.includes('gap')||l.includes('margin')||l.includes('width')||l.includes('spread')||l.includes('distance')||l.includes('length')||l.includes('radius')||l.includes('angle')) return 'supplies a measured geometric quantity whose datum and resolution should be written down';
  if(l.includes('customer')||l.includes('instrument')||l.includes('job')||l.includes('quote')) return 'identifies the record so its result is not attached to the wrong instrument or work order';
  if(type==='select') return 'classifies an observed condition; choose “unknown” or “not tested” instead of guessing when available';
  if(type==='textarea'||type==='text') return 'captures the exact observation, list, or requirement that the result must preserve';
  return 'provides a measured or counted input; confirm the allowed range and repeat the reading before relying on it';
};

export function toolDepthHtml(t,defs,related){
  const d=toolDepth[t.slug];
  if(!d) throw new Error(`Missing depth content: ${t.slug}`);
  const fields=t.fields.map(k=>{const [label,type]=defs[k];return `<dt>${label}</dt><dd>${fieldRole(label,type)}.</dd>`}).join('');
  const links=related(t).map(r=>`<li><a href="${r.slug.startsWith('/')?r.slug:'/tools/'+r.slug+'.html'}">${r.title}</a> — ${r.description}</li>`).join('');
  return `<article class="tool-depth prose">
    <section><h2>What this tool is for</h2><p>${t.description} ${categoryContext[t.category]}</p><p>Use it when you can describe the current state and need a defensible next check. It is not a shortcut around inspection: preserve the starting state, change one variable, and verify the result under the same conditions.</p></section>
    <section><h2>Before you begin</h2><p>${d.prepare}</p><ul><li>Use a stable, tuned instrument unless the page specifically investigates tuning.</li><li>Name the physical reference, unit, and test condition beside every important number.</li><li>Keep the original measurements so any reversible change can be returned to baseline.</li></ul></section>
    <section><h2>Input guide</h2><dl>${fields}</dl><p>Input labels describe evidence, not targets. A placeholder demonstrates format only; it is never a recommendation for a particular guitar.</p></section>
    <section><h2>How the result should be read</h2><p>${d.interpret}</p><p>Read priorities from top to bottom, but stop as soon as new evidence contradicts an earlier assumption. Save or print the result ticket with the entered conditions so another person can reproduce the decision.</p></section>
    <section><h2>Method and logic</h2><p>${d.method}</p><p>The page keeps calculation and diagnostic claims deliberately bounded. Display rounding improves readability, while the underlying logic uses entered values; descriptive branches report relative tendencies and the evidence needed to confirm them.</p></section>
    <section><h2>Worked example</h2><p>${d.example}</p><p>The example demonstrates reasoning, not a universal setup specification. Substitute real measurements and repeat the final test before accepting the next action.</p></section>
    <section><h2>Assumptions and limitations</h2><p>${d.limits}</p><p>Instrument design, service history, measurement error, and player technique can outweigh a calculator or checklist. Where manufacturer instructions exist for the exact hardware, use those instructions and record the revision consulted.</p></section>
    <section><h2>Safety and stop conditions</h2><p>Stop for abnormal resistance, cracking, heat, odor, electrical sensation, moving wood or joints, a measurement that cannot be repeated, or any step that would remove material without a confirmed cause. Secure strings and stored mechanical energy before hardware work. Refer structural, fret-cutting, mains-powered, or uncertain repairs to a qualified technician.</p></section>
    <section><h2>Related workflow</h2><ul>${links}</ul><p>Open the related page that answers the next unresolved question; do not run every tool as if every system needs adjustment.</p></section>
  </article>`;
}

export const hubIntroductions={
 diagnostics:['Start with the symptom, then locate where and when it occurs. The safest diagnostic path uses controlled comparisons before adjustment.','Use Setup Wizard for an unknown sequence, the focused buzz, high-action, tuning, or intonation tools for a repeatable symptom, and the instrument checklists when a complete baseline is needed.','A diagnosis remains provisional until a physical test confirms it. Record “not tested” rather than converting missing evidence into certainty.'],
 measurement:['A useful number includes its datum, unit, instrument position, string state, and measurement resolution. This bench turns raw readings into comparable records.','Converters handle units; relief, action, scale, pickup, gauge, and tension pages explain what can—and cannot—be inferred from those readings.','Do not chase a target copied from another instrument. Repeat the measurement, correlate it with the symptom, and follow manufacturer limits for the exact hardware.'],
 documents:['The record bench connects intake, permission, measurements, quote, work performed, final test, and maintenance without mixing those stages.','Choose the smallest document that preserves the decision: an intake for arrival facts, a quote for proposed cost, a job sheet for actual work, or a before/after card for measured change.','Browser-generated records stay on the device unless you save or print them. Apply your own privacy, retention, tax, consent, and consumer-law procedures.'],
 inspection:['Inspection is a structured search for visible evidence and uncertainty, not a promise about hidden condition or market value.','Walk from identity and structure through neck, frets, hardware, acoustic behavior, electronics, and playability. Use known-good test equipment and obtain permission before access.','Keep observation separate from diagnosis and repair pricing. Hidden repairs, authenticity, ownership, and future reliability require independent verification.'],
 electronics:['Begin outside the guitar: level down, known-good cable, direct signal path, comparison instrument, room, and safe amplifier or interface.','Once the source domain is isolated, use the phase, wiring, pot, capacitor, and coil-mode pages to define passive-circuit requirements and tradeoffs.','Never open an amplifier, power supply, or mains device. Maker wire colors are not universal, so document lead functions before soldering.'],
 luthier:['This bench converts named datums into fret, spacing, radius, multiscale, angle, tremolo, and shim comparisons before material is marked.','Use a reference page to define measurements, calculate with one unit system, verify invariants, and transfer only through a calibrated physical print or full drawing.','Every result omits some combination of tolerances, kerf, material behavior, hardware range, and ergonomics. Mock up and measure again before irreversible work.']
};

export function hubDepthHtml(key,label,list){const x=hubIntroductions[key];return `<article class="prose hub-depth"><h2>How to use the ${label} bench</h2><p>${x[0]}</p><h2>Choose the right starting point</h2><p>${x[1]}</p><p>This category contains ${list.length} focused tools. Read each page’s preparation and limitation sections before entering values, then follow only the related workflow that resolves the next uncertainty.</p><h2>Evidence standard</h2><p>${x[2]}</p><ol><li>Preserve the starting condition.</li><li>Change or test one variable.</li><li>Retune or reset the test condition.</li><li>Repeat the same measurement.</li><li>Record remaining uncertainty.</li></ol><h2>When to stop</h2><p>Stop when evidence conflicts, a datum is unclear, hardware reaches a limit, or the next step becomes structural, energized, or irreversible. A qualified technician can inspect conditions that browser inputs cannot represent.</p></article>`}

const articleDetails={
  'setup-order':['A guitar that still changes pitch after every bend is not ready for relief or intonation judgment. Stabilize the strings first; after relief changes, retune before measuring action, and leave saddle intonation until the speaking geometry is settled.',['/tools/guitar-setup-wizard.html','/tools/setup-measurement-sheet.html']],
  'measure-neck-relief':['For example, record “0.18 mm at fret 8, capo fret 1, string held at fret 17” rather than “slight relief.” Repeat the gap after tuning and positioning the guitar the same way; route a localized upper-fret buzz to fret/action inspection instead of assuming more curvature.',['/tools/neck-relief-measurement.html','/tools/fret-buzz-diagnostic.html']],
  'used-guitar-inspection':['If output cuts out only when the plug moves, record the cable substitution and physical trigger without declaring that the jack must be replaced. Add untested truss-rod range and hidden repairs to uncertainty, then decide whether an in-person technician assessment belongs in the purchase budget.',['/tools/used-guitar-inspection.html','/tools/guitar-condition-report.html']],
  'document-guitar-setup':['A reproducible entry names tuning, string set, relief span, action fret, pickup measurement condition, and the final full-neck test. Preserve an unresolved rattle or limited bridge travel in the after record instead of turning “improved” into an unsupported promise.',['/tools/setup-measurement-sheet.html','/tools/before-after-setup-card.html']],
  'diagnose-guitar-hum-safely':['Hum that disappears with a known-good cable points to a different next action than hum shared by two guitars in one room. Touch behavior and pickup-position changes are observations only; they never authorize protective-earth changes or opening powered equipment.',['/tools/ground-hum-diagnostic.html','/reference/pickup-wiring-terms.html']],
  'repair-intake-workflow':['When a customer reports “cuts out after ten minutes,” preserve that wording, record visible arrival facts separately, and obtain diagnostic permission before assigning a cause. Connect authorized cost to a quote and actual work to a job sheet so proposed and completed work cannot be confused.',['/tools/guitar-repair-intake.html','/tools/repair-quote-generator.html','/tools/parts-labor-job-sheet.html']],
  'choosing-pot-capacitor-values':['A 500 kΩ pot generally loads a passive pickup less than a 250 kΩ pot, while a 47 nF tone capacitor usually allows a darker rolled-off range than 22 nF. Neither comparison predicts exact sound because pickup inductance, cable capacitance, tolerance, and amplifier input remain in the circuit.',['/tools/potentiometer-value-selector.html','/tools/tone-capacitor-comparison.html']],
  'string-gauge-setup-effects':['A move from 9–42 to 10–46 while tuning down mixes an upward gauge effect with a downward frequency effect. Use published unit weights for an exact supported comparison, then stabilize and recheck nut movement, relief, tremolo position, action, and intonation.',['/tools/string-gauge-change-planner.html','/tools/string-tension-matcher.html']],
  'print-actual-size':['A PDF can have the correct A4 or Letter page box and still be scaled by a viewer or driver. Print at Actual size, measure both independent bars, reject any out-of-tolerance output, and align tiled overlap marks before a fret coordinate is transferred.',['/tools/fret-slot-print-template.html','/tools/fret-position-template.html']],
  'measure-string-spacing':['With mixed gauges, equal-center spacing preserves identical center intervals while physical open gaps shrink beside heavier strings. Equal-edge-gap spacing preserves open space and therefore changes center coordinates; compare both layouts against real fret bevel and outside margins.',['/tools/nut-string-spacing.html','/tools/bridge-string-spacing.html']],
  'unit-conversion':['A measured 1.6 mm action is about 0.0630 inch and close to 4/64 inch. Keep 1.6 mm as the observed value if that matches the tool resolution; the fraction is a communication aid and does not add precision.',['/tools/string-action-converter.html','/tools/setup-measurement-sheet.html']],
  'measurement-points':['“Action 2.0 mm” is incomplete until the record says which fret, which string, top of fret to underside of string, tuning, and instrument position. The same discipline applies to relief span, pickup clearance at the last fret, and scale witness points.',['/tools/neck-relief-measurement.html','/tools/pickup-height-planner.html','/tools/scale-length-identifier.html']],
  'string-tension-formula':['At fixed unit weight and scale, dropping one whole step multiplies frequency by about 0.891 and tension by about 0.794. Exact comparisons between products still require their published unit weights; diameter alone cannot supply the missing construction data.',['/tools/string-tension-matcher.html','/tools/alternate-tuning-string-selector.html']],
  'pickup-wiring-terms':['A four-conductor humbucker can expose individual coil starts and finishes, but the manufacturer’s colors must be mapped before series, parallel, or split switching is planned. Magnetic polarity and electrical phase are related observations, not interchangeable terms.',['/tools/pickup-wiring-selector.html','/tools/pickup-phase-troubleshooter.html']],
  'fret-position-formula':['For a 25.5-inch scale, fret 12 is 12.750 inches from the nut and fret 24 is 19.125 inches. These invariant checks verify the equal-tempered coordinates; practical saddle compensation changes the string endpoint, not the nominal fret-slot formula.',['/tools/fret-position-template.html','/tools/multiscale-fretboard-planner.html']],
  'geometry-measurement':['A radius calculation using chord and sagitta fails if the straight chord and perpendicular center depth are confused. Likewise, a neck-angle projection must use rise and run from one side-view datum, and a print calibration must be confirmed on paper rather than on screen.',['/tools/fretboard-radius-matcher.html','/tools/neck-angle-planner.html','/guides/print-actual-size.html']],
  'pot-values':['Choose a passive pot as one part of total pickup loading. A higher resistance usually preserves more high-frequency response, but actual tolerance, tone wiring, cable capacitance, pickup inductance, and amplifier input can make two nominally identical installations behave differently.',['/tools/potentiometer-value-selector.html','/tools/tone-capacitor-comparison.html']],
  'series-parallel-coil-split':['Series usually provides the fullest humbucker output; parallel is generally clearer and may retain cancellation; a split normally lowers output and loses full cancellation. Confirm accessible coil leads and switch contacts before choosing a mode.',['/tools/series-parallel-coil-split-selector.html','/tools/pickup-wiring-selector.html']],
  'equal-center-vs-equal-gap':['Six strings across a fixed outer-center spread have one equal-center interval, but mixed diameters create different open gaps. Equal-gap layout redistributes the centers; neither method determines a universal outside margin or safe nut-slot geometry.',['/tools/nut-string-spacing.html','/guides/measure-string-spacing.html']]
};

export function articleDepthHtml(title,description,kind='guide',slug=''){
  const noun=kind==='reference'?'reference':kind==='comparison'?'comparison':'guide';
  const detail=articleDetails[slug];if(!detail)throw new Error(`Missing article depth detail: ${slug}`);
  const links=detail[1].map(x=>`<li><a href="${x}">${x.split('/').at(-1).replace('.html','').replaceAll('-',' ')}</a> — continue when that page answers the next unresolved measurement or decision.</li>`).join('');
  return `<section class="article-depth"><h2>Scope of this ${noun}</h2><p>${description} Use ${title} to make a repeatable decision for this named task, not to impose one specification on every instrument.</p><h2>Practical example</h2><p>${detail[0]}</p><h2>Record the conditions</h2><p>For ${title}, write down instrument type, tuning, installed strings, relevant hardware, climate when material, physical datum, unit, tool resolution, and the result before and after change. A result from this ${noun} is comparable only when its method travels with the number.</p><h2>Verification checklist</h2><ol><li>For ${title}, confirm the starting state and exact question.</li><li>Repeat its critical measurements from the same reference.</li><li>Compare its result with direct observation and applicable maker documentation.</li><li>Change one reversible variable where the task permits.</li><li>Retest the named symptom and preserve unresolved exceptions.</li></ol><h2>Related workflow</h2><ul>${links}</ul><h2>Limits</h2><p>${title} cannot inspect hidden structure, material condition, service history, or player technique. Stop this ${noun} workflow for electrical hazards, abnormal resistance, structural movement, conflicting readings, or unplanned material removal.</p></section>`;
}
