import {readFile,readdir} from 'node:fs/promises';import path from 'node:path';import vm from 'node:vm';import {calculateQuote,calculateTensionSet,rcCutoffHz} from './assets/calculations.js';
const root=path.join(process.cwd(),'site');let failures=[];const assert=(ok,msg)=>{if(!ok)failures.push(msg)};
async function walk(d){let out=[];for(const e of await readdir(d,{withFileTypes:true})){const p=path.join(d,e.name);out.push(...(e.isDirectory()?await walk(p):[p]))}return out}
const files=await walk(root),html=files.filter(f=>f.endsWith('.html')),rel=f=>path.relative(root,f).replaceAll('\\','/');
const titles=new Map(),urls=new Set(html.map(rel)),inbound=new Map([...urls].map(x=>[x,0]));
for(const f of html){const s=await readFile(f,'utf8'),r=rel(f);let title=s.match(/<title>(.*?)<\/title>/)?.[1],desc=s.match(/<meta name="description" content="([^"]+)/)?.[1],canon=s.match(/<link rel="canonical" href="([^"]+)/)?.[1];assert(title,`${r}: missing title`);assert(desc&&desc.length>=40,`${r}: missing/short description`);assert(canon===`https://guitarsetuplab.com/${r==='index.html'?'':r}`,`${r}: canonical mismatch`);assert((s.match(/<h1[ >]/g)||[]).length===1,`${r}: H1 count`);assert((s.match(/G-TGT88WMVDG/g)||[]).length===2,`${r}: GA4 missing/duplicate`);assert(!/hello@|support@|example\.com/i.test(s),`${r}: forbidden email/domain`);const emails=[...s.matchAll(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/gi)].map(x=>x[0]);assert(emails.every(x=>x==='canghun13@naver.com'),`${r}: unknown email`);let json=s.match(/<script type="application\/ld\+json">(.*?)<\/script>/s)?.[1];try{JSON.parse(json)}catch{assert(false,`${r}: invalid JSON-LD`)}if(title){assert(!titles.has(title),`${r}: duplicate title with ${titles.get(title)}`);titles.set(title,r)}
 for(const m of s.matchAll(/(?:href|src)="(\/[^"]+)"/g)){let u=m[1].split(/[?#]/)[0].slice(1);if(!u)u='index.html';if(u.endsWith('/'))u+='index.html';assert(files.some(x=>rel(x)===u),`${r}: broken internal reference ${m[1]}`);if(inbound.has(u)&&u!==r)inbound.set(u,inbound.get(u)+1)}
}
for(const [r,count] of inbound)if(!['index.html','404.html'].includes(r))assert(count>0,`${r}: orphan page`);
const js=await readFile(path.join(root,'assets/app.js'),'utf8');try{new vm.Script(js.replace(/^import .*$/m,''))}catch(e){assert(false,`JavaScript syntax: ${e.message}`)}assert(Object.keys((js.match(/'[^']+':d=>/g)||{})).length!==0,'tool logic missing');
for(const slug of ['fret-buzz-diagnostic','string-action-converter','scale-length-identifier','setup-measurement-sheet','guitar-repair-intake','repair-quote-generator','parts-labor-job-sheet','customer-approval-checklist','maintenance-schedule','ground-hum-diagnostic','pickup-phase-troubleshooter','pickup-wiring-selector','potentiometer-value-selector','tone-capacitor-comparison','series-parallel-coil-split-selector','string-tension-matcher']) assert(js.includes(`'${slug}':d=>`),`${slug}: dedicated logic missing`);
const map=await readFile(path.join(root,'sitemap.xml'),'utf8');for(const f of html.filter(x=>rel(x)!=='404.html')){let r=rel(f);assert(map.includes(`https://guitarsetuplab.com/${r==='index.html'?'':r}`),`${r}: absent from sitemap`)}assert(!map.includes('/404.html'),'404 listed in sitemap');
assert((await readFile(path.join(root,'robots.txt'),'utf8')).includes('Sitemap: https://guitarsetuplab.com/sitemap.xml'),'robots sitemap missing');assert((await readFile(path.join(root,'llms.txt'),'utf8')).includes('safety-first'),'llms.txt incomplete');
const toolPages=html.filter(f=>rel(f).startsWith('tools/'));assert(toolPages.length===30,`expected 30 tools, got ${toolPages.length}`);for(const f of toolPages){const s=await readFile(f,'utf8');assert(s.includes('data-tool='),`${rel(f)}: no interactive tool root`);assert(s.includes('Run tool'),`${rel(f)}: no submit`);assert(s.includes('Reset'),`${rel(f)}: no reset`);assert(s.includes('Stop if'),`${rel(f)}: no safety stop`) }
const quote=calculateQuote({laborText:'Setup labor | 2.5 | 60',partsText:'Strings | 2 | 12.50',taxPercent:10,discount:5,deposit:50});assert(quote.laborCents===15000,'quote labor subtotal');assert(quote.partsCents===2500,'quote parts subtotal');assert(quote.taxCents===1700,'quote tax');assert(quote.totalCents===18700,'quote total');assert(quote.balanceCents===13700,'quote balance');let invalidQuoteRejected=false;try{calculateQuote({laborText:'bad row',partsText:''})}catch{invalidQuoteRejected=true}assert(invalidQuoteRejected,'invalid quote row accepted');
const standard=calculateTensionSet({instrument:'guitar',scaleIn:25.5,tuning:'E standard',gauges:'10p,13p,17p,26w,36w,46w'});const expected=[16.2,15.4,16.6,18.4,19.5,17.5];assert(!standard.error&&!standard.unsupported.length,'standard tension unavailable');standard.rows.forEach((x,i)=>assert(Math.abs(x.tension-expected[i])<.15,`tension fixture string ${i+1}`));const shortScale=calculateTensionSet({instrument:'guitar',scaleIn:24.75,tuning:'E standard',gauges:'10p,13p,17p,26w,36w,46w'});const longScale=calculateTensionSet({instrument:'guitar',scaleIn:27,tuning:'E standard',gauges:'10p,13p,17p,26w,36w,46w'});const dropD=calculateTensionSet({instrument:'guitar',scaleIn:25.5,tuning:'Drop D',gauges:'10p,13p,17p,26w,36w,46w'});assert(shortScale.total<standard.total&&longScale.total>standard.total,'scale tension direction');assert(dropD.rows[5].tension<standard.rows[5].tension,'drop D tension direction');const bass=calculateTensionSet({instrument:'bass',scaleIn:34,tuning:'E standard',gauges:'45w,65w,80w,100w'});assert(!bass.error&&bass.total>100,'bass fixture');assert(calculateTensionSet({instrument:'guitar',scaleIn:10,tuning:'E standard',gauges:'10p,13p,17p,26w,36w,46w'}).error,'invalid scale accepted');assert(calculateTensionSet({instrument:'guitar',scaleIn:25.5,tuning:'E standard',gauges:'10p,13p,17p,25w,36w,46w'}).unsupported.includes('25w'),'unsupported gauge accepted');assert(Math.abs(rcCutoffHz(500,22)-14.4686)<.01,'RC fixture');
assert(html.length===54,`expected 54 public HTML pages, got ${html.length}`);
const css=await readFile(path.join(root,'assets/style.css'),'utf8'),narrow=await readFile(path.join(root,'assets/narrow.css'),'utf8');assert(css.includes('@media print')&&css.includes('.tool-form')&&css.includes('.actions{display:none}'),'print stylesheet incomplete');assert(narrow.includes('.result td{overflow-wrap:anywhere}')&&narrow.includes('.result th{overflow-wrap:normal')&&narrow.includes('@media print'),'long-value or print wrapping rules missing');
for(const f of [...html,...['sitemap.xml','robots.txt','llms.txt','CNAME','favicon.svg','assets/style.css','assets/narrow.css','assets/calculations.js','assets/app.js'].map(x=>path.join(root,x))]){const r=rel(f);const deployed=path.join(process.cwd(),r);assert((await readFile(f)).equals(await readFile(deployed)),`${r}: root deployment mirror differs`) }
console.log(`Checked ${html.length} HTML pages, ${toolPages.length} tool pages, metadata, links, assets, structured data, sitemap, and JS syntax.`);if(failures.length){console.error(failures.join('\n'));process.exit(1)}console.log('PASS: 0 failures');
