import {readFile,readdir} from 'node:fs/promises';import path from 'node:path';import vm from 'node:vm';
const root=path.join(process.cwd(),'site');let failures=[];const assert=(ok,msg)=>{if(!ok)failures.push(msg)};
async function walk(d){let out=[];for(const e of await readdir(d,{withFileTypes:true})){const p=path.join(d,e.name);out.push(...(e.isDirectory()?await walk(p):[p]))}return out}
const files=await walk(root),html=files.filter(f=>f.endsWith('.html')),rel=f=>path.relative(root,f).replaceAll('\\','/');
const titles=new Map(),urls=new Set(html.map(rel));
for(const f of html){const s=await readFile(f,'utf8'),r=rel(f);let title=s.match(/<title>(.*?)<\/title>/)?.[1],desc=s.match(/<meta name="description" content="([^"]+)/)?.[1],canon=s.match(/<link rel="canonical" href="([^"]+)/)?.[1];assert(title,`${r}: missing title`);assert(desc&&desc.length>=40,`${r}: missing/short description`);assert(canon===`https://guitarsetuplab.com/${r==='index.html'?'':r}`,`${r}: canonical mismatch`);assert((s.match(/<h1[ >]/g)||[]).length===1,`${r}: H1 count`);assert((s.match(/G-TGT88WMVDG/g)||[]).length===2,`${r}: GA4 missing/duplicate`);assert(!/hello@|support@|example\.com/i.test(s),`${r}: forbidden email/domain`);const emails=[...s.matchAll(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/gi)].map(x=>x[0]);assert(emails.every(x=>x==='canghun13@naver.com'),`${r}: unknown email`);let json=s.match(/<script type="application\/ld\+json">(.*?)<\/script>/s)?.[1];try{JSON.parse(json)}catch{assert(false,`${r}: invalid JSON-LD`)}if(title){assert(!titles.has(title),`${r}: duplicate title with ${titles.get(title)}`);titles.set(title,r)}
 for(const m of s.matchAll(/(?:href|src)="(\/[^"]+)"/g)){let u=m[1].split(/[?#]/)[0].slice(1);if(!u)u='index.html';if(u.endsWith('/'))u+='index.html';assert(files.some(x=>rel(x)===u),`${r}: broken internal reference ${m[1]}`)}
}
const js=await readFile(path.join(root,'assets/app.js'),'utf8');try{new vm.Script(js)}catch(e){assert(false,`JavaScript syntax: ${e.message}`)}assert(Object.keys((js.match(/'[^']+':d=>/g)||{})).length!==0,'tool logic missing');
for(const slug of ['fret-buzz-diagnostic','string-action-converter','scale-length-identifier','setup-measurement-sheet']) assert(js.includes(`'${slug}':d=>`),`${slug}: dedicated logic missing`);
const map=await readFile(path.join(root,'sitemap.xml'),'utf8');for(const f of html.filter(x=>rel(x)!=='404.html')){let r=rel(f);assert(map.includes(`https://guitarsetuplab.com/${r==='index.html'?'':r}`),`${r}: absent from sitemap`)}assert(!map.includes('/404.html'),'404 listed in sitemap');
assert((await readFile(path.join(root,'robots.txt'),'utf8')).includes('Sitemap: https://guitarsetuplab.com/sitemap.xml'),'robots sitemap missing');assert((await readFile(path.join(root,'llms.txt'),'utf8')).includes('safety-first'),'llms.txt incomplete');
const toolPages=html.filter(f=>rel(f).startsWith('tools/'));assert(toolPages.length===18,`expected 18 tools, got ${toolPages.length}`);for(const f of toolPages){const s=await readFile(f,'utf8');assert(s.includes('data-tool='),`${rel(f)}: no interactive tool root`);assert(s.includes('Run tool'),`${rel(f)}: no submit`);assert(s.includes('Reset'),`${rel(f)}: no reset`);assert(s.includes('Stop if'),`${rel(f)}: no safety stop`) }
for(const f of [...html,...['sitemap.xml','robots.txt','llms.txt','CNAME','favicon.svg','assets/style.css','assets/narrow.css','assets/app.js'].map(x=>path.join(root,x))]){const r=rel(f);const deployed=path.join(process.cwd(),r);assert((await readFile(f)).equals(await readFile(deployed)),`${r}: root deployment mirror differs`) }
console.log(`Checked ${html.length} HTML pages, ${toolPages.length} tool pages, metadata, links, assets, structured data, sitemap, and JS syntax.`);if(failures.length){console.error(failures.join('\n'));process.exit(1)}console.log('PASS: 0 failures');
